name: Publish NuGet Package to GitHub

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ConsoleUI.Tests
    
    - name: Build
      run: dotnet build ConsoleUI.Tests --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ConsoleUI.Tests --configuration Release --no-build --verbosity normal

  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ConsoleUI
    
    - name: Build
      run: dotnet build ConsoleUI --configuration Release --no-restore
    
    - name: Pack
      run: dotnet pack ConsoleUI --configuration Release --no-build --output ./artifacts
    
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push ./artifacts/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}